version: '3.8'

services:
  voltorb-flip:
    container_name: voltorb-flip
    build: .
    ports:
      - '3002:3002'
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
