export const UPDATE_CLICKED = "UPDATE_CLICKED";
export const FLIP_ALL = "FLIP_ALL";
export const UPDATE_CURRENT_TILE = "UPDATE_CURRENT_TILE";
export const UPDATE_MEMOS = "UPDATE_MEMOS";
export const UPDATE_ROUND_SCORE = "UPDATE_ROUND_SCORE";
export const UPDATE_TOTAL_SCORE = "UPDATE_TOTAL_SCORE";
